
---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Infrastructure:
    - Proxmox:
        href: "http://proxmox.home:8006"
        description: Proxmox Server
        icon: "si-proxmox"
        widget:
          type: proxmox
          url: "https://proxmox.home:8006"
          username: "homepage@pam!homepage"
          password: "{{HOMEPAGE_VAR_PROXMOX}}"
          verify_ssl: false
          node: proxmox
    
    - Proxmox Backup:
        href: "http://backup.home:8007"
        description: Proxmox Backup Server
        icon: "si-proxmox"
        widget:
            type: proxmoxbackupserver
            url: "https://backup.home:8007"
            username: "root@pam!homepage"
            password: "{{HOMEPAGE_VAR_PBS}}"
            verify_ssl: false

    - TrueNAS:
        href: "http://truenas.home"
        description: TrueNAS Storage
        icon: "si-truenas"
        widget:
          type: truenas
          url: "http://truenas.home"
          username: "truenas_admin"
          password: "{{HOMEPAGE_VAR_PASSWORD}}"
          enablePools: true
          version: 2

    - Arcane:
        href: "http://docker.home:3552"
        description: Docker Dashboard
        icon: "si-docker"
        widget:
          type: arcane
          url: "http://docker.home:3552"
          env: 0
          key: "{{HOMEPAGE_VAR_ARCANE}}"
          fields: ["running", "stopped", "image_updates", "images_unused"] 
    - Borg:
        href: "http://borg.home:8081"
        description: Borg Backup Server
        icon: "si-borgbackup"
        ping: borg.home


- Network:
    - Unifi Controller:
        href: "https://unifi.ui.com/"
        description: Unifi Network Controller
        icon: "si-ubiquiti"
        widget:
          type: unifi
          url: "https://192.168.1.1"
          key: "{{HOMEPAGE_VAR_UNIFI}}"

    # - Pi-hole:
    #     href: "http://192.168.1.100:8080/admin"
    #     description: DNS and Ad Blocking
    #     icon: "si-pihole"
    #     widget:
    #       type: pihole
    #       url: "http://192.168.1.100:8080"
    #       key: "{{HOMEPAGE_VAR_PASSWORD}}"
    #       version: 6
    # - Pi-hole 2:
    #     href: "http://192.168.1.101:8080/admin"
    #     description: DNS and Ad Blocking
    #     icon: "si-pihole"
    #     widget:
    #       type: pihole
    #       url: "http://192.168.1.101:8080"
    #       key: "{{HOMEPAGE_VAR_PASSWORD}}"
    #       version: 6
    - Technitium:
        href: "http://192.168.1.10:5380"
        description: DHCP and DNS Server
        icon: "si-dash"
        widget:
          type: technitium
          url: "http://192.168.1.10:5380"
          key: "{{HOMEPAGE_VAR_TECHNITIUM}}"
          range: LastDay
          fields: ["totalQueries", "totalClients", "totalBlocked"]  

    - Speedtest:
        href: "http://speedtest.home"
        description: Speedtest CLI
        icon: "si-speedtest"
        widget:
          type: speedtest
          url: "http://speedtest.home"
          bitratePrecision: 2
          key: "{{HOMEPAGE_VAR_SPEEDTEST}}"
    - Homelable:
        icon: si-homebridge
        ping: homelable.home
        description: Home Network Visualizer
        href: http://homelable.home:3000
    # - Caddy:
    #     href: "http://dockerpi.home"
    #     description: Caddy Dashboard
    #     icon: "si-caddy"
    #     widget:
    #       type: caddy
    #       url: "http://192.168.1.100:2019"
    - Beszel:
        href: "http://docker.home:8090"
        description: Network Graph Visualization
        icon: "si-bazel"
        ping: docker.home
        widget:
          type: beszel
          url: "http://docker.home:8090"
          username: "{{HOMEPAGE_VAR_EMAIL}}"
          password: "{{HOMEPAGE_VAR_PASSWORD}}"
          version: 2
    - Grafana:
        href: "http://docker.home:3001"
        description: Observability Dashboards
        icon: si-grafana
        widget:
            type: grafana
            version: 2 # optional, default is 1
            url: http://docker.home:3001
            username: "admin"
            password: "{{HOMEPAGE_VAR_PASSWORD}}"
            fields: ["dashboards", "datasources", "totalalerts"]
    
- Arr:
    - Jellyfin:
        href: "http://jellyfin.home:8096"
        description: Media Server
        icon: "si-jellyfin"
        widget:
            type: jellyfin
            url: "http://jellyfin.home:8096"
            key: "{{HOMEPAGE_VAR_JELLYFIN}}"
        enableBlocks: true
    - Radarr:
        href: "http://radarr.home:7878"        
        description: Movie Management
        icon: "si-radarr"
        widget:
            type: radarr
            url: "http://radarr.home:7878"
            key: "{{HOMEPAGE_VAR_RADARR}}"
        enableQueue: true
    - Sonarr:
        href: "http://sonarr.home:8989"
        description: TV Show Management
        icon: "si-sonarr"
        widget:
            type: sonarr
            url: "http://sonarr.home:8989"
            key: "{{HOMEPAGE_VAR_SONARR}}"
            enableQueue: true
    - Lazy Librarian:
        href: "http://docker.home:5299"        
        description: eBook Management
        icon: "si-bookstack"
    - SABnzbd:
        href: "http://sabnzbd.home:7777"        
        description: Usenet Downloader
        icon: "si-abdownloadmanager"
        widget:
            type: sabnzbd
            url: "http://sabnzbd.home:7777"
            key: "{{HOMEPAGE_VAR_SABNZBD}}"
    - Yamtrack:
        href: "http://yamtrack.home:8000"
        description: Catalog tracker
        icon: "si-trakt"
        ping: yamtrack.home
- Other:
    - AI:
        - Ollama:
            href: "http://ollama-vm.home:11434"
            description: Local AI Model Hosting
            icon: "si-ollama"
        - Bifrost:
            href: "http://ollama-vm.home:8080"
            description: Local LLM Router
            icon: "si-frontify"
        - OpenRouter:
            href: "https://openrouter.ai/activity"
            description: Cloud LLM Router
            icon: "si-openrouter"
        - Spacebot:
            href: "http://spacebot.home:19898"
            description: Spacebot Agent Orchestrator
            icon: "si-starship"
            ping: spacebot.home
        - Paperclip:
            href: "http://paperclip.home:3100"
            description: Paperclip Agent Orchestrator
            icon: "si-purescript"
            ping: paperclip.home
        - Hermes:
            href: "http://hermes.home:9119/"
            description: Hermes Agent Dashboard
            icon: "si-hermes"
            ping: hermes.home

    - Applications: 
        - Immich:
            href: "http://immich.home:2283"
            description: Photo Management
            icon: "si-immich"
            widget:
                type: immich
                url: "http://immich.home:2283"
                key: "{{HOMEPAGE_VAR_IMMICH}}"
                version: 2
                fields: ["photos", "videos", "storage"]

        - Paperless:
            href: "http://paperless.home:8000"
            description: Document Management
            icon: "si-paperlessngx"
            widget:
                type: paperlessngx
                url: "http://paperless.home:8000"
                username: "{{HOMEPAGE_VAR_NAME}}"
                password: "{{HOMEPAGE_VAR_PASSWORD}}"
                version: 2
        - FreshRSS:
            icon: si-freshrss
            description: RSS Reader
            href: http://freshrss.home
            widget:
                type: freshrss
                url: "http://freshrss.home"
                username: "{{HOMEPAGE_VAR_NAME}}"
                password: "{{HOMEPAGE_VAR_PASSWORD}}"
        - n8n:
            icon: si-n8n
            description: Workflow and Automations
            href: "http://n8n.home:5678"
        - Actual Budget:
            icon: si-actualbudget
            description: Personal Finance Workflow
            href: "http://docker.home:5006"

    - Misc:
        - Proxmox Scripts:
            icon: si-googledocs
            description: Proxmox Community Scripts
            href: https://community-scripts.org/

        - SURVIVE:
            icon: si-fireship
            description: Offline Grab and Go Server
            ping: survive.home
            href: http://survive.home/

        - Concert Watcher:
            href: "http://spacebot.home:7474"
            icon: "si-applemusic"
            description: Spotify playslist concert notifier
        
        - BirdNet Home:
            icon: si-thunderbird
            ping: birdnet.home
            description: Wildlife Sounds - Home Instance 
            href: http://birdnet.home:8080
        - BirdNet Lake:
            icon: si-thunderbird
            ping: dockerlake.lake
            description: Wildlife Sounds - Lake Instance
            href: http://dockerlake.lake:8080




