
---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Infrastructure:
    - Proxmox:
        href: "http://proxmox.home:8006"
        description: Proxmox Server
        icon: "si-proxmox"
        widget:
          type: proxmox
          url: "https://proxmox.home:8006"
          username: "homepage@pam!homepage"
          password: "{{HOMEPAGE_VAR_PROXMOX}}"
          verify_ssl: false
          node: proxmox
    
    - Proxmox Backup:
        href: "http://backup.home:8007"
        description: Proxmox Backup Server
        icon: "si-proxmox"
        widget:
            type: proxmoxbackupserver
            url: "https://backup.home:8007"
            username: "root@pam!homepage"
            password: "{{HOMEPAGE_VAR_PBS}}"
            verify_ssl: false

    - TrueNAS:
        href: "http://truenas.home"
        description: TrueNAS Storage
        icon: "si-truenas"
        widget:
          type: truenas
          url: "http://truenas.home"
          username: "truenas_admin"
          password: "{{HOMEPAGE_VAR_PASSWORD}}"
          enablePools: true
          version: 2

    - Arcane:
        href: "http://docker.home:3552"
        description: Docker Dashboard
        icon: "si-docker"
        widget:
          type: arcane
          url: "http://docker.home:3552"
          env: 0
          key: "{{HOMEPAGE_VAR_ARCANE}}"
          fields: ["running", "stopped", "image_updates", "images_unused"] 


- Network:
    - Unifi Controller:
        href: "https://unifi.ui.com/"
        description: Unifi Network Controller
        icon: "si-ubiquiti"
        widget:
          type: unifi
          url: "https://192.168.1.1"
          key: "{{HOMEPAGE_VAR_UNIFI}}"

    # - Pi-hole:
    #     href: "http://192.168.1.100:8080/admin"
    #     description: DNS and Ad Blocking
    #     icon: "si-pihole"
    #     widget:
    #       type: pihole
    #       url: "http://192.168.1.100:8080"
    #       key: "{{HOMEPAGE_VAR_PASSWORD}}"
    #       version: 6
    # - Pi-hole 2:
    #     href: "http://192.168.1.101:8080/admin"
    #     description: DNS and Ad Blocking
    #     icon: "si-pihole"
    #     widget:
    #       type: pihole
    #       url: "http://192.168.1.101:8080"
    #       key: "{{HOMEPAGE_VAR_PASSWORD}}"
    #       version: 6
    - Technitium:
        href: "http://192.168.1.10:5380"
        description: DHCP and DNS Server
        icon: "si-dash"
        widget:
          type: technitium
          url: "http://192.168.1.10:5380"
          key: "{{HOMEPAGE_VAR_TECHNITIUM}}"
          range: LastDay
          fields: ["totalQueries", "totalClients", "totalBlocked"]  

    - Speedtest:
        href: "http://speedtest.home"
        description: Speedtest CLI
        icon: "si-speedtest"
        widget:
          type: speedtest
          url: "http://speedtest.home"
          bitratePrecision: 2
          key: "{{HOMEPAGE_VAR_SPEEDTEST}}"
    - Homelable:
        icon: si-homebridge
        ping: homelable.home
        href: http://homelable.home:3000
    # - Caddy:
    #     href: "http://dockerpi.home"
    #     description: Caddy Dashboard
    #     icon: "si-caddy"
    #     widget:
    #       type: caddy
    #       url: "http://192.168.1.100:2019"

    
- Arr:
    - Jellyfin:
        href: "http://jellyfin.home:8096"
        description: Media Server
        icon: "si-jellyfin"
        widget:
            type: jellyfin
            url: "http://jellyfin.home:8096"
            key: "{{HOMEPAGE_VAR_JELLYFIN}}"
        enableBlocks: true
    - Radarr:
        href: "http://radarr.home:7878"        
        description: Movie Management
        icon: "si-radarr"
        widget:
            type: radarr
            url: "http://radarr.home:7878"
            key: "{{HOMEPAGE_VAR_RADARR}}"
        enableQueue: true
    - Sonarr:
        href: "http://sonarr.home:8989"
        description: TV Show Management
        icon: "si-sonarr"
        widget:
            type: sonarr
            url: "http://sonarr.home:8989"
            key: "{{HOMEPAGE_VAR_SONARR}}"
            enableQueue: true
    - Lazy Librarian:
        href: "http://docker.home:5299"        
        description: eBook Management
        icon: "si-bookstack"
    - SABnzbd:
        href: "http://sabnzbd.home:7777"        
        description: Usenet Downloader
        icon: "si-abdownloadmanager"
        widget:
            type: sabnzbd
            url: "http://sabnzbd.home:7777"
            key: "{{HOMEPAGE_VAR_SABNZBD}}"
- Other:
    - AI:
        - Ollama:
            href: "http://ollama-vm.home:11434"
            description: Local AI Model Hosting
            icon: "si-ollama"
        - Spacebot:
            href: "http://spacebot.home:19898"
            description: Spacebot
            icon: "si-starship"
            ping: spacebot.home
        - Paperclip:
            href: "http://paperclip.home:3100"
            description: Paperclip
            icon: "si-purescript"
            ping: paperclip.home
        - Bifrost:
            href: "http://ollama-vm.home:8080"
            description: Bifrost
            icon: "si-frontify"
        - OpenRouter:
            href: "https://openrouter.ai/activity"
            description: OpenRouter
            icon: "si-openrouter"
    - Applications: 
        - Immich:
            href: "http://immich.home:2283"
            description: Photo Management
            icon: "si-immich"
            widget:
                type: immich
                url: "http://immich.home:2283"
                key: "{{HOMEPAGE_VAR_IMMICH}}"
                version: 2
                fields: ["photos", "videos", "storage"]

        - Paperless:
            href: "http://paperless.home:8000"
            description: Document Management
            icon: "si-paperlessngx"
            widget:
                type: paperlessngx
                url: "http://paperless.home:8000"
                username: "{{HOMEPAGE_VAR_NAME}}"
                password: "{{HOMEPAGE_VAR_PASSWORD}}"
                version: 2

        - Concert Watcher:
            href: "http://spacebot.home:7474"
            description: Concert Watcher
            icon: "si-applemusic"

    - Misc:
        - Proxmox Scripts:
            icon: si-googledocs
            href: https://community-scripts.org/

        - SURVIVE:
            icon: si-fireship
            href: http://survive/

        - FreshRSS:
            icon: si-freshrss
            href: http://freshrss.home
            widget:
                type: freshrss
                url: "http://freshrss.home"
                username: "{{HOMEPAGE_VAR_NAME}}"
                password: "{{HOMEPAGE_VAR_PASSWORD}}"
        - BirdNet Home:
            icon: si-thunderbird
            ping: birdnet.home
            href: http://birdnet.home:8080
        - BirdNet Lake:
            icon: si-thunderbird
            ping: dockerlake.home
            href: http://dockerlake.home:8080




