---
title: Homelab
headerStyle: clean
background:
  image: /images/ocean.jpg
  saturate: 50
  brightness: 50
  opacity: 70
theme: dark
useEqualHeights: false
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true
  hideVisitURL: true
hideVersion: false
hideErrors: true
statusStyle: "dot"
layout:
  Infrastructure:
    header: true
    style: column
    rowHeight: 40px
  Network:
    header: true
    style: column
    rowHeight: 40px
  Arr:
    header: true
    style: column
    rowHeight: 40px
  Other:
    header: false
    style: row
    columns: 3
    AI:
      header: true
      style: column
      rowHeight: 40px
    Applications:
      header: true
      style: column
      rowHeight: 40px
    Misc:
      header: true
      style: column
      rowHeight: 40px